# Задания на повторение материала

Импортирование необходимых библиотек:

In [1]:
# Import the necessary packages

import numpy as np
import pandas as pd

Теперь к заданиям:

1. Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно

In [4]:
# Create Numpy array

a = np.arange(12, 24)

# Check the result

print(a)

[12 13 14 15 16 17 18 19 20 21 22 23]


2. Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.

In [5]:
# Create 2D Numpy array

a = a.reshape(2, 6)

# Check the result

print(a)

[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [6]:
# Create 2D Numpy array

b = a.argsort(axis = 0)

# Check the result

print(b)

[[0 0 0 0 0 0]
 [1 1 1 1 1 1]]


In [7]:
# Create 2D Numpy array

c = a + a

# Check the result

print(c)

[[24 26 28 30 32 34]
 [36 38 40 42 44 46]]


In [8]:
# Create 2D Numpy array

d = a.reshape(6, 2) + np.ones((6, 2))

# Check the result

print(d)

[[ 13.  14.]
 [ 15.  16.]
 [ 17.  18.]
 [ 19.  20.]
 [ 21.  22.]
 [ 23.  24.]]


In [9]:
# Create 2D Numpy array

e = np.sqrt(a.reshape(6, 2))

# Check the result

print(e)

[[ 3.46410162  3.60555128]
 [ 3.74165739  3.87298335]
 [ 4.          4.12310563]
 [ 4.24264069  4.35889894]
 [ 4.47213595  4.58257569]
 [ 4.69041576  4.79583152]]


3. Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).

In [10]:
# Create 2D Numpy array

a1 = a.reshape(2, -1)

# Check the result

print(a1)

[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [11]:
# Create 2D Numpy array

b1 = a.reshape(12, -1)

# Check the result

print(b1)

[[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]


In [12]:
# Create 2D Numpy array

c1 = a.reshape(6, -1)

# Check the result

print(c1)

[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]


In [13]:
# Create 2D Numpy array

d1 = a.reshape(-1, 3)

# Check the result

print(d1)

[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]


In [14]:
# Create 2D Numpy array

e1 = a.reshape(-1, 1)

# Check the result

print(e1)

[[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]


4. Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?

In [15]:
# Create Numpy arrays

a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
b = a.reshape(12, 1)

# Check

a.ndim == b.ndim

False

5. Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.

In [16]:
# Create Numpy array with 3 rows and 4 columns

a = np.random.randn(3, 4)

# Check

a.size

12

In [17]:
b = a.flatten()

# Check

b.size

12

6. Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.

In [18]:
# Create Numpy array from 20 to 0 exclusive and with interval 2

a = np.arange(20, 0, -2)

# Check the result

print(a)

[20 18 16 14 12 10  8  6  4  2]


7. Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b?

In [19]:
# Create Numpy array b with 1 row and 10 columns

b = np.arange(20, 1, -2)
b.reshape(1, 10)

# Check the result

print(b)

[20 18 16 14 12 10  8  6  4  2]


8. Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.

In [20]:
# Add a and b, where a consists of 0 and b - 1

a = np.zeros((2, 2))

b = np.ones((3, 2))

v = np.concatenate((a, b), axis = 0)

# Check

v.size

10

9. Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?

In [24]:
# Create Numpy array with values from 0 to 12 and then reshape it

A = np.arange(12).reshape(4, 3)

# Check

print(A)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [25]:
# Create matrix At from a

At = A.T

# Check

print(At)

[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]


In [26]:
# Create matrix B by multiplying a and At

B = A.dot(At)

# Check

print(B)

[[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]


In [29]:
# If the matrix determinant is ZERO, the inverse matrix will NOT work

np.linalg.det(B)

0.0

10. Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.

In [30]:
# Create random number generator

np.random.seed(42)

11. Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно. 

In [31]:
# Create Numpy array c

c = np.random.randint(0, 16, 16)

# Check

print(c)

[ 6  3 12 14 10  7 12  4  6  9  2  6 10 10  7  4]


12. Поменяйте его форму так, чтобы получилась квадратная матрица C. Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10. Вычислите определитель, ранг и обратную матрицу D_inv для D.

In [32]:
C = c.reshape(4, 4)
C.shape

(4, 4)

In [33]:
D = B + C * 10
D

array([[ 65,  44, 143, 172],
       [114, 120, 206, 162],
       [ 83, 176, 169, 272],
       [132, 222, 282, 342]])

In [34]:
D_d = np.linalg.det(D)

In [35]:
np.linalg.matrix_rank(D)

4

In [36]:
D_inv = np.linalg.inv(D)
D_inv

array([[ 0.00935396,  0.04486532,  0.05897517, -0.07286055],
       [-0.01503577, -0.00122896, -0.00192971,  0.00967873],
       [-0.00356692, -0.01782828, -0.04152146,  0.04326178],
       [ 0.00909091, -0.00181818,  0.01272727, -0.01090909]])

13. Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. Убедитесь, что в матрице D_inv остались только нули и единицы. С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4.  Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.

In [37]:
D_inv = np.where(D_inv < 0, 0, 1)
D_inv

array([[1, 1, 1, 0],
       [0, 0, 0, 1],
       [0, 0, 0, 1],
       [1, 0, 1, 0]])

In [38]:
E = np.where(D_inv > 0, B, C)
print(E)

[[  5  14  23  14]
 [ 10   7  12 122]
 [  6   9   2 212]
 [ 32  10 212   4]]
